channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - numpy
  - mpich
  - pyvista[all]
  - scipy
  - pytest
  - pint
  - gmsh
  - pip
pip:
  - git+https://github.com/BAMresearch/FenicsXConcrete