name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - numpy
  - mpich
  - pyvista[all]
  - scipy
  - h5py=3.10.0
  - hdf5>=1.14.2,<1.14.4
  - git
  - pip
pip:
  - trame_jupyter_extension
