name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - numpy
  - mpich
  - pyvista[all]
  - pytest
  - gmsh
  - pint
  - jsonschema
  - pandas
  - pyproj
  - tqdm
  - scipy
  - git
  - pip
pip:
  - trame_jupyter_extension
