
name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - mpich
  - pyvista[all]
  - scipy
  - pip
pip:
  - trame_jupyter_extension


"""
name: demonstrator
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx=0.6.0
  - numpy
  - mpich
  - pyvista[all]
  - scipy
  - pip
  - ipykernel
pip:
  - git+https://github.com/BAMresearch/FenicsXConcrete
"""